apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.componentName }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "roboshop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "roboshop.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "roboshop.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.componentName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.componentName }}:{{ .Values.appVersion }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: {{ .Values.healthEndpoint}}
              port: {{ .Values.appPort}}
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.healthEndpoint}}
              port: {{ .Values.appPort}}
            initialDelaySeconds: 10
            periodSeconds: 5
          {{- if .Values.externalSecret.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.componentName }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
