{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.componentName }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: roboshop-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.componentName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.componentName }}
{{- end }}
